import Head from "next/head";
import Slide from "components/Sliders";
import bannerImg from "public/img/slider4.jpg";
import ListIconCategories from "components/category/ListIconCategories";
import Banner from "components/Banner";
import Brand from "components/Brand";
import Feature from "@/components/feature";
import Testimonials from "@/components/Testimonials";
import ShegeftAngizan from "@/components/productsSlider/ShegeftAngizan";
import TopProduct from "@/components/productsSlider/TopProduct";

export default function Home() {
  return (
    <>
      <Head>
        <title>Belzioo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*  A div that contains all the components that are going to be displayed on the home page. */}
      <div className="md:px-7 overflow-x-hidden px-1 space-y-5 mt-5">
        <Slide />
        <ListIconCategories />
        <ShegeftAngizan />
        
        <Banner img={bannerImg} link="test" title="test" />
        <Brand />
        <TopProduct />
        <Testimonials />
        <Feature className=" w-10 sm:w-16 sm:h-16 md:w-24 h-12 md:h-20" />
      </div>
    </>
  );
}
