import Head from "next/head";
import Slide from "components/Sliders";
import bannerImg from "public/img/slider4.jpg";
import ListIconCategories from "components/category/ListIconCategories";
import Banner from "components/Banner";
import TopProducts from "components/Product/ShegeftAngizan";
import Brand from "components/Brand";
import TopProduct from "@/components/Product/TopProduct";
import Feature from "@/components/feature";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="md:px-7 px-1 space-y-5 mt-5">
        <Slide />
        <ListIconCategories />
        <TopProducts />
        <Banner img={bannerImg} link="test" title="test" />
        <Brand/>
        <TopProduct/>
        <Feature/>
      </div>
    </>
  );
}
